import type { Metadata } from "next";
import "./globals.css";
import Headers from "./components/header";

export const metadata: Metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
        <body className='bg-green-100 text-green-800'>
            <Headers />
            <main className="container m-auto my-3">
                {children}
            </main>
        </body>
    </html>
  );
}
